from unidecode import unidecode

class Bible:
    def getBooksPtBRName(self, i):
        booksPtBrName = [
            "Gênesis",
            "Êxodo",
            "Levítico",
            "Números",
            "Deuteronômio",
            "Josué",
            "Juízes",
            "Rute",
            "1 Samuel",
            "2 Samuel",
            "1 Reis",
            "2 Reis",
            "1 Crônicas",
            "2 Crônicas",
            "Esdras",
            "Neemias",
            "Ester",
            "Jób",
            "Salmos",
            "Provérbios",
            "Eclesiastes",
            "Cânticos",
            "Isaías",
            "Jeremias",
            "Lamentações",
            "Ezequiel",
            "Dn",
            "Oséias",
            "Joel",
            "Amós",
            "Obadias",
            "Jonas",
            "Miquéias",
            "Naum",
            "Habacuque",
            "Sofonias",
            "Ageu",
            "Zacarias",
            "Malaquias",
            "Mateus",
            "Marcos",
            "Lucas",
            "João",
            "Atos",
            "Romanos",
            "1 Coríntios",
            "2 Coríntios",
            "Gálatas",
            "Efésios",
            "Filipenses",
            "Colossenses",
            "1 Tessalonicenses",
            "2 Tessalonicenses",
            "1 Timóteo",
            "2 Timóteo",
            "Tito",
            "Filemom",
            "Hebreus",
            "Tiago",
            "1 Pedro",
            "2 Pedro",
            "1 João",
            "2 João",
            "3 João",
            "Judas",
            "Apocalipse",
        ]

        return unidecode(booksPtBrName[i])
    
    def getBooksPtBRAbbreviation(self, i):
        booksAbbreviation = [
            "Gn",
            "Êx",
            "Lv",
            "Nm",
            "Dt",
            "Js",
            "Jz",
            "Rt",
            "1 Sm",
            "2 Sm",
            "1 Rs",
            "2 Rs",
            "1 Cr",
            "2 Cr",
            "Ed",
            "Ne",
            "Et",
            "Jó",
            "Sl",
            "Pv",
            "Ec",
            "Ct",
            "Is",
            "Jr",
            "Lm",
            "Ez",
            "Dn",
            "Os",
            "Jl",
            "Am",
            "Ob",
            "Jn",
            "Mq",
            "Na",
            "Hc",
            "Sf",
            "Ag",
            "Zc",
            "Ml",
            "Mt",
            "Mc",
            "Lc",
            "Jo",
            "At",
            "Rm",
            "1 Co",
            "2 Co",
            "Gl",
            "Ef",
            "Fp",
            "Cl",
            "1 Ts",
            "2 Ts",
            "1 Tm",
            "2 Tm",
            "Tt",
            "Fm",
            "Hb",
            "Tg",
            "1 Pe",
            "2 Pe",
            "1 Jo",
            "2 Jo",
            "3 Jo",
            "Jd",
            "Ap",
        ]

        return booksAbbreviation[i]
    
    def getbooksChapterNumber(self, i):
        booksChapterNumber = [
            "50",
            "40",
            "27",
            "36",
            "34",
            "24",
            "21",
            "4",
            "31",
            "24",
            "22",
            "25",
            "29",
            "36",
            "10",
            "13",
            "10",
            "42",
            "150",
            "31",
            "12",
            "8",
            "66",
            "52",
            "5",
            "48",
            "12",
            "14",
            "3",
            "9",
            "1",
            "4",
            "7",
            "3",
            "3",
            "3",
            "2",
            "14",
            "4",
            "28",
            "16",
            "24",
            "21",
            "26",
            "16",
            "16",
            "13",
            "6",
            "6",
            "4",
            "4",
            "5",
            "3",
            "6",
            "4",
            "3",
            "1",
            "13",
            "5",
            "5",
            "3",
            "5",
            "1",
            "1",
            "1",
            "22"
        ]

        return booksChapterNumber[i]